-- 코드를 작성해주세요
WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS(
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID
    FROM ECOLI_DATA JOIN FIRST_GEN ON ECOLI_DATA.PARENT_ID = FIRST_GEN.ID
)

SELECT A.ID
FROM ECOLI_DATA A
JOIN SECOND_GEN B ON A.PARENT_ID = B.ID
ORDER BY A.ID;