-- 코드를 입력하세요
SELECT DISTINCT(CR.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCR ON CR.CAR_ID = CRCR.CAR_ID
WHERE MONTH(CRCR.START_DATE) = 10 AND CR.CAR_TYPE = '세단'
ORDER BY CR.CAR_ID DESC;